// Command Neon-cli is a CLI + REPL for the Neon SDK,
// built on the boru engine. Positional arguments are joined into a
// single boru expression and evaluated; with no arguments, falls into
// a REPL. Generated by sdkgen go-cli target.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	"github.com/boru-lang/boru/eng/go/parser"
	sdk "github.com/voxgig-sdk/neon-sdk/go"
)

// prompt is the REPL prompt prefix (matches the SDK slug).
const prompt = "neon"

// entitiesHelp is the space-separated entity list shown by /help.
const entitiesHelp = "anonymize anonymized_branch_status api_key auth auth_legacy available_preload_library backup_schedule branch branch_ai_gateway branch_operation branch_schema branch_schema_compare branch_storage bucket bucket_objects_list connection_uri consumption create_credential credential current_user_info custom_domain data_api database email_provider email_server empty endpoint endpoint_operation function jwk masking_rule member neon_auth_allow_localhost neon_auth_config neon_auth_create_integration neon_auth_create_new_user neon_auth_email_and_password_config neon_auth_email_server_config neon_auth_integration neon_auth_magic_link_config neon_auth_oauth_provider neon_auth_organization_config neon_auth_phone_number_config neon_auth_plugin_config neon_auth_redirect_uri_whitelist_domain neon_auth_transfer_auth_provider_project neon_auth_webhook_config neon_function neon_function_deployment operation org_api_key_create org_api_key_revoke org_api_keys_list_response_item organization organization_invitation presign project project_branch_log_field project_branch_log_field_value project_branch_logs_query project_member project_member_role project_permission project_recover project_transfer_request region role role_operation role_password send_neon_auth_test_email snapshot spending_limit trigger update_neon_auth_user_role vpc_endpoint"

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

// usage prints the CLI help (for --help / -h). No client or network setup.
func usage(out io.Writer) {
	fmt.Fprintf(out, "%s-cli — boru-driven CLI + REPL for the %s SDK\n\n", prompt, prompt)
	fmt.Fprintln(out, "Usage:")
	fmt.Fprintf(out, "  %s-cli [--help] [<boru expression>]\n\n", prompt)
	fmt.Fprintln(out, "With arguments, they are joined into a single boru expression and")
	fmt.Fprintln(out, "evaluated against the API. With no arguments, starts an interactive REPL.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Words:    list / load / update <query?> <entity>")
	fmt.Fprintln(out, "Entities:", entitiesHelp)
	fmt.Fprintln(out, "Env:      NEON_APIKEY (api key), NEON_BASE (base url override)")
	fmt.Fprintln(out, "REPL:     /help  /quit")
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
	// --help / -h: print usage and exit before any config or network setup.
	for _, a := range args {
		if a == "--help" || a == "-h" {
			usage(out)
			return 0
		}
	}

	// Configure from the environment: NEON_APIKEY carries the API key and
	// NEON_BASE optionally overrides the API base URL (e.g. production).
	// Both injectable by a secrets vault. Unset -> nil config defaults.
	var opts map[string]any
	if apikey := os.Getenv("NEON_APIKEY"); apikey != "" {
		opts = map[string]any{"apikey": apikey}
	}
	if base := os.Getenv("NEON_BASE"); base != "" {
		if opts == nil {
			opts = map[string]any{}
		}
		opts["base"] = base
	}
	client := sdk.NewNeonSDK(opts)

	r, err := eng.NewRegistry()
	if err != nil {
		fmt.Fprintf(errOut, "registry: %v\n", err)
		return 1
	}
	registerSDKWords(r, client)
	if err := r.Err(); err != nil {
		fmt.Fprintf(errOut, "word registration: %v\n", err)
		return 1
	}
	r.SetParseFunc(parser.Parse)
	r.InitRootContext()
	r.MarkReady()

	if len(args) > 0 {
		return evalOnce(r, strings.Join(args, " "), out, errOut)
	}
	repl(r, in, out)
	return 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
	values, err := parser.Parse(src)
	if err != nil {
		fmt.Fprintf(errOut, "parse: %v\n", err)
		return 1
	}
	result, err := eng.NewTop(r).Run(values)
	if err != nil {
		fmt.Fprintf(errOut, "error: %v\n", err)
		return 1
	}
	for _, v := range result {
		fmt.Fprintln(out, v.String())
	}
	return 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for {
		fmt.Fprintf(out, "%s> ", prompt)
		if !scanner.Scan() {
			fmt.Fprintln(out)
			return
		}
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		switch line {
		case "/quit", "/q", "/exit":
			return
		case "/help", "/h", "/?":
			fmt.Fprintln(out, "words:    list / load / update <query?> <entity>")
			fmt.Fprintln(out, "entities:", entitiesHelp)
			fmt.Fprintln(out, "meta:     /help  /quit")
			continue
		}
		values, err := parser.Parse(line)
		if err != nil {
			fmt.Fprintf(out, "  parse error: %v\n", err)
			continue
		}
		result, err := eng.NewTop(r).Run(values)
		if err != nil {
			fmt.Fprintf(out, "  error: %v\n", err)
			continue
		}
		for _, v := range result {
			fmt.Fprintln(out, v.String())
		}
	}
}
