// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/neon-sdk/go"
)

func registerSDKWords(r *eng.Registry, client *sdk.NeonSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.NeonSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.NeonSDK, name string) (sdk.NeonEntity, error) {
	switch strings.ToLower(name) {
	case "anonymize":
		return client.Anonymize(nil), nil
	case "anonymized_branch_status":
		return client.AnonymizedBranchStatus(nil), nil
	case "api_key":
		return client.ApiKey(nil), nil
	case "auth":
		return client.Auth(nil), nil
	case "auth_legacy":
		return client.AuthLegacy(nil), nil
	case "available_preload_library":
		return client.AvailablePreloadLibrary(nil), nil
	case "backup_schedule":
		return client.BackupSchedule(nil), nil
	case "branch":
		return client.Branch(nil), nil
	case "branch_ai_gateway":
		return client.BranchAiGateway(nil), nil
	case "branch_operation":
		return client.BranchOperation(nil), nil
	case "branch_schema":
		return client.BranchSchema(nil), nil
	case "branch_schema_compare":
		return client.BranchSchemaCompare(nil), nil
	case "branch_storage":
		return client.BranchStorage(nil), nil
	case "bucket":
		return client.Bucket(nil), nil
	case "bucket_objects_list":
		return client.BucketObjectsList(nil), nil
	case "connection_uri":
		return client.ConnectionUri(nil), nil
	case "consumption":
		return client.Consumption(nil), nil
	case "create_credential":
		return client.CreateCredential(nil), nil
	case "credential":
		return client.Credential(nil), nil
	case "current_user_info":
		return client.CurrentUserInfo(nil), nil
	case "custom_domain":
		return client.CustomDomain(nil), nil
	case "data_api":
		return client.DataApi(nil), nil
	case "database":
		return client.Database(nil), nil
	case "email_provider":
		return client.EmailProvider(nil), nil
	case "email_server":
		return client.EmailServer(nil), nil
	case "empty":
		return client.Empty(nil), nil
	case "endpoint":
		return client.Endpoint(nil), nil
	case "endpoint_operation":
		return client.EndpointOperation(nil), nil
	case "function":
		return client.Function(nil), nil
	case "jwk":
		return client.Jwk(nil), nil
	case "masking_rule":
		return client.MaskingRule(nil), nil
	case "member":
		return client.Member(nil), nil
	case "neon_auth_allow_localhost":
		return client.NeonAuthAllowLocalhost(nil), nil
	case "neon_auth_config":
		return client.NeonAuthConfig(nil), nil
	case "neon_auth_create_integration":
		return client.NeonAuthCreateIntegration(nil), nil
	case "neon_auth_create_new_user":
		return client.NeonAuthCreateNewUser(nil), nil
	case "neon_auth_email_and_password_config":
		return client.NeonAuthEmailAndPasswordConfig(nil), nil
	case "neon_auth_email_server_config":
		return client.NeonAuthEmailServerConfig(nil), nil
	case "neon_auth_integration":
		return client.NeonAuthIntegration(nil), nil
	case "neon_auth_magic_link_config":
		return client.NeonAuthMagicLinkConfig(nil), nil
	case "neon_auth_oauth_provider":
		return client.NeonAuthOauthProvider(nil), nil
	case "neon_auth_organization_config":
		return client.NeonAuthOrganizationConfig(nil), nil
	case "neon_auth_phone_number_config":
		return client.NeonAuthPhoneNumberConfig(nil), nil
	case "neon_auth_plugin_config":
		return client.NeonAuthPluginConfig(nil), nil
	case "neon_auth_redirect_uri_whitelist_domain":
		return client.NeonAuthRedirectUriWhitelistDomain(nil), nil
	case "neon_auth_transfer_auth_provider_project":
		return client.NeonAuthTransferAuthProviderProject(nil), nil
	case "neon_auth_webhook_config":
		return client.NeonAuthWebhookConfig(nil), nil
	case "neon_function":
		return client.NeonFunction(nil), nil
	case "neon_function_deployment":
		return client.NeonFunctionDeployment(nil), nil
	case "operation":
		return client.Operation(nil), nil
	case "org_api_key_create":
		return client.OrgApiKeyCreate(nil), nil
	case "org_api_key_revoke":
		return client.OrgApiKeyRevoke(nil), nil
	case "org_api_keys_list_response_item":
		return client.OrgApiKeysListResponseItem(nil), nil
	case "organization":
		return client.Organization(nil), nil
	case "organization_invitation":
		return client.OrganizationInvitation(nil), nil
	case "presign":
		return client.Presign(nil), nil
	case "project":
		return client.Project(nil), nil
	case "project_branch_log_field":
		return client.ProjectBranchLogField(nil), nil
	case "project_branch_log_field_value":
		return client.ProjectBranchLogFieldValue(nil), nil
	case "project_branch_logs_query":
		return client.ProjectBranchLogsQuery(nil), nil
	case "project_member":
		return client.ProjectMember(nil), nil
	case "project_member_role":
		return client.ProjectMemberRole(nil), nil
	case "project_permission":
		return client.ProjectPermission(nil), nil
	case "project_recover":
		return client.ProjectRecover(nil), nil
	case "project_transfer_request":
		return client.ProjectTransferRequest(nil), nil
	case "region":
		return client.Region(nil), nil
	case "role":
		return client.Role(nil), nil
	case "role_operation":
		return client.RoleOperation(nil), nil
	case "role_password":
		return client.RolePassword(nil), nil
	case "send_neon_auth_test_email":
		return client.SendNeonAuthTestEmail(nil), nil
	case "snapshot":
		return client.Snapshot(nil), nil
	case "spending_limit":
		return client.SpendingLimit(nil), nil
	case "trigger":
		return client.Trigger(nil), nil
	case "update_neon_auth_user_role":
		return client.UpdateNeonAuthUserRole(nil), nil
	case "vpc_endpoint":
		return client.VpcEndpoint(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
